apiVersion: batch/v1
kind: Job
metadata:
  name: expense-management-service-migration-job
  namespace: expense-management-service
  labels:
    app: expense-management-service
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: expense-management-migration-job
          image: 246299324052.dkr.ecr.us-west-1.amazonaws.com/expense-management-migrations:1.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db-credentials
      restartPolicy: Never