"""update date defaults

Revision ID: ca175252f48d
Revises: ac3f1cc9f539
Create Date: 2023-08-25 08:48:56.626400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca175252f48d"
down_revision: Union[str, None] = "ac3f1cc9f539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # # Create a new temporary table with the new structure
    # op.create_table(
    #     "temp_category",
    #     sa.Column("id", sa.String, primary_key=True),
    #     sa.Column("name", sa.String),
    #     sa.Column("description", sa.String),
    #     sa.Column("created_at", sa.DateTime),
    #     sa.Column("updated_at", sa.DateTime),
    # )

    # # Copy data from the old table to the new table
    # op.execute("INSERT INTO temp_category SELECT * FROM category;")

    # # Drop the old table
    # op.drop_table("category")

    # # Rename the new table to the old table's name
    # op.rename_table("temp_category", "category")
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
